version = 1

[[annotations]]
path = "go.mod"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "go.sum"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "code-examples/*"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docker-files/*"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "etc/**"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "testdata/**"
SPDX-FileCopyrightText = "Winni Neessen <wn@neessen.dev>"
SPDX-License-Identifier = "MIT"
